import type { BlockDefinition, Field } from "./types";

const linkFields: Field[] = [
  { key: "label", label: "লেবেল", type: "text" },
  { key: "href", label: "লিংক", type: "text", placeholder: "/about-us" },
];

const backgroundField: Field = {
  key: "background",
  label: "ব্যাকগ্রাউন্ড",
  type: "select",
  options: [
    { label: "সাদা", value: "white" },
    { label: "হালকা ধূসর", value: "slate" },
  ],
};

export const BLOCKS: BlockDefinition[] = [
  {
    type: "page-body",
    label: "পেজের মূল কন্টেন্ট",
    description: "এই পেজের বিল্ট-ইন কন্টেন্ট — লুকানো যাবে, মুছা যাবে না",
    group: "page",
    icon: "page",
    fields: [],
    defaults: {},
    fixed: true,
  },
  {
    type: "hero",
    label: "হিরো ব্যানার",
    description: "ডাক্তারের নাম, পরিচিতি ও ছবি সহ প্রধান ব্যানার",
    group: "page",
    icon: "hero",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "nameLine1", label: "নাম (প্রথম লাইন)", type: "text" },
      { key: "nameLine2", label: "নাম (দ্বিতীয় লাইন)", type: "text" },
      { key: "degrees", label: "ডিগ্রি", type: "text" },
      { key: "university", label: "বিশ্ববিদ্যালয়", type: "text" },
      { key: "position", label: "পদবি", type: "text" },
      { key: "hospital", label: "হাসপাতাল", type: "text" },
      { key: "primaryLabel", label: "প্রধান বাটন", type: "text" },
      { key: "primaryPhone", label: "প্রধান বাটন ফোন", type: "tel" },
      { key: "secondaryLabel", label: "দ্বিতীয় বাটন", type: "text" },
      { key: "secondaryHref", label: "দ্বিতীয় বাটন লিংক", type: "text" },
      { key: "image", label: "ডাক্তারের ছবি", type: "image" },
      { key: "showFloating", label: "ফ্লোটিং কার্ড দেখাবেন?", type: "boolean" },
      { key: "floatingTitle", label: "ফ্লোটিং কার্ড শিরোনাম", type: "text" },
      {
        key: "floatingSubtitle",
        label: "ফ্লোটিং কার্ড উপশিরোনাম",
        type: "text",
      },
    ],
    defaults: {
      badge: "অর্থোপেডিক্স বিশেষজ্ঞ ও ট্রমা সার্জন",
      nameLine1: "ডা. গাজী মোহাম্মদ",
      nameLine2: "আরিফুল ইসলাম (ভিলীয়া)",
      degrees: "এমবিবিএস, বিসিএস, এমএস (অর্থোপেডিক্স সার্জারী)",
      university: "বঙ্গবন্ধু শেখ মুজিব মেডিকেল বিশ্ববিদ্যালয় (BSMMU), ঢাকা",
      position: "সহকারী রেজিস্ট্রার — ক্যাজুয়ালটি বিভাগ",
      hospital: "কুমিল্লা মেডিকেল কলেজ হাসপাতাল",
      primaryLabel: "অ্যাপয়েন্টমেন্ট নিন",
      primaryPhone: "+8801858405083",
      secondaryLabel: "আরও জানুন",
      secondaryHref: "/about-us",
      image: "/doctor-img.png",
      showFloating: true,
      floatingTitle: "তিনটি চেম্বারে",
      floatingSubtitle: "নিয়মিত রোগী দেখছেন",
    },
  },
  {
    type: "stats",
    label: "পরিসংখ্যান (ভিডিও ব্যাকগ্রাউন্ড)",
    description: "ভিডিও ব্যাকগ্রাউন্ডের উপর সংখ্যাসহ বিবরণ",
    group: "page",
    icon: "stats",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "headingLine1", label: "শিরোনাম (প্রথম লাইন)", type: "text" },
      { key: "headingLine2", label: "শিরোনাম (দ্বিতীয় লাইন)", type: "text" },
      { key: "video", label: "ব্যাকগ্রাউন্ড ভিডিও পাথ", type: "text" },
      { key: "years", label: "অভিজ্ঞতা (বছর)", type: "text" },
      { key: "surgeries", label: "সার্জারি সংখ্যা", type: "text" },
      { key: "trauma", label: "ট্রমা অপারেশন সংখ্যা", type: "text" },
      { key: "patients", label: "রোগী সংখ্যা", type: "text" },
    ],
    defaults: {
      badge: "সেবার পরিসংখ্যান",
      headingLine1: "সংখ্যার অন্তরালে",
      headingLine2: "একেকটি সুস্থতার গল্প",
      video: "/intro-video.mp4",
      years: "৫+",
      surgeries: "৫০০০+",
      trauma: "১০০০+",
      patients: "৫০,০০০+",
    },
  },
  {
    type: "treatments",
    label: "চিকিৎসা সেবা প্রিভিউ",
    description: "ছবিসহ চিকিৎসা সেবার কার্ড গ্রিড",
    group: "page",
    icon: "grid",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "buttonLabel", label: "বাটন টেক্সট", type: "text" },
      { key: "buttonHref", label: "বাটন লিংক", type: "text" },
      {
        key: "items",
        label: "চিকিৎসা তালিকা",
        type: "list",
        itemLabel: "চিকিৎসা",
        fields: [
          { key: "label", label: "নাম", type: "text" },
          { key: "desc", label: "বিবরণ", type: "textarea" },
          { key: "image", label: "ছবি", type: "image" },
          { key: "href", label: "লিংক", type: "text" },
        ],
      },
    ],
    defaults: {
      badge: "বিশেষায়িত সেবা",
      heading: "আমাদের চিকিৎসা সেবাসমূহ",
      buttonLabel: "সকল চিকিৎসার বিবরণ দেখুন",
      buttonHref: "/our-treatments",
      items: [
        {
          label: "হাঁটু ব্যথা",
          desc: "হাঁটুর লিগামেন্ট, কার্টিলেজ ও বিভিন্ন জটিলতার আধুনিক চিকিৎসা",
          image: "/knee.jpg",
          href: "/our-treatments/knee-pain-treatment-cumilla",
        },
        {
          label: "কোমর ও মেরুদণ্ড",
          desc: "ডিস্ক প্রোল্যাপ্স, সাইটিকা ও মেরুদণ্ডের তীব্র ব্যথা ব্যবস্থাপনা",
          image: "/low-back-pain.jpg",
          href: "/our-treatments/back-pain-treatment-cumilla",
        },
        {
          label: "কাঁধ ও জয়েন্টের সমস্যা",
          desc: "ফ্রোজেন শোল্ডার, কাঁধের জয়েন্ট ও পেশির দীর্ঘমেয়াদী সমস্যার সমাধান",
          image: "/shoulder.webp",
          href: "/our-treatments/shoulder-joint-pain-treatment-cumilla",
        },
        {
          label: "স্পোর্টস ইনজুরি",
          desc: "খেলোয়াড়দের পেশি ও লিগামেন্ট ইনজুরির বিশেষায়িত আধুনিক চিকিৎসা",
          image: "/sports.jpg",
          href: "/our-treatments/sports-injury-treatment-cumilla",
        },
        {
          label: "মেরুদণ্ডের সমস্যা ও ট্রমা",
          desc: "দুর্ঘটনাজনিত হাড় ভাঙা, স্থানচ্যুতি ও জটিল ট্রমা সার্জারি পরবর্তী সেবা",
          image: "/spine.jpg",
          href: "/our-treatments/spine-trauma-treatment-cumilla",
        },
        {
          label: "হাতের কব্জি ও পায়ের পাতা",
          desc: "কব্জি, পায়ের গোড়ালি ও রগ বা পেশির নানান রোগের সমাধান",
          image: "/wrist.jpg",
          href: "/our-treatments/wrist-foot-pain-treatment-cumilla",
        },
      ],
    },
  },
  {
    type: "chambers",
    label: "চেম্বার ও সময়সূচি",
    description: "চেম্বারের ঠিকানা, সময় ও ফোন নম্বর",
    group: "page",
    icon: "map",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "subtitle", label: "উপশিরোনাম", type: "textarea" },
      { key: "mainPhone", label: "প্রধান ফোন", type: "tel" },
      { key: "altPhone", label: "বিকল্প ফোন", type: "tel" },
      {
        key: "items",
        label: "চেম্বার তালিকা",
        type: "list",
        itemLabel: "চেম্বার",
        fields: [
          { key: "name", label: "নাম", type: "text" },
          { key: "logo", label: "লোগো", type: "image" },
          { key: "address", label: "ঠিকানা", type: "textarea" },
          { key: "days", label: "দিন", type: "text" },
          { key: "time", label: "সময়", type: "text" },
          { key: "offDays", label: "বন্ধের দিন", type: "text" },
          { key: "mapUrl", label: "ম্যাপ লিংক", type: "url" },
          {
            key: "theme",
            label: "রঙ",
            type: "select",
            options: [
              { label: "লাল", value: "red" },
              { label: "সবুজ", value: "green" },
              { label: "নীল", value: "blue" },
            ],
          },
          {
            key: "showAltPhone",
            label: "বিকল্প ফোন দেখাবেন?",
            type: "boolean",
          },
        ],
      },
    ],
    defaults: {
      badge: "চেম্বার ও সময়সূচি",
      heading: "সরাসরি সাক্ষাৎ ও সিরিয়াল",
      subtitle:
        "রোগীদের সুবিধার্থে ৩টি ভিন্ন লোকেশনে এবং সুনির্দিষ্ট সময়ে চেম্বার পরিচালনা করা হচ্ছে।",
      mainPhone: "+8801612371696",
      altPhone: "+8801858405083",
      items: [
        {
          name: "কুমিল্লা ট্রমা সেন্টার",
          logo: "/cumilla-logo.png",
          address:
            "রুম ৭০৬,  ৭ম তলা (লিফট-৬), নতুন ভবন, রাণীর বাজার রোড, কান্দিরপাড়, কুমিল্লা",
          days: "শনিবার থেকে বুধবার",
          time: "দুপুর ২:০০ — বিকেল ৫:০০",
          offDays: "বৃহস্পতি ও শুক্রবার বন্ধ",
          mapUrl:
            "https://www.google.com/maps/place/Cumilla+Trauma+Centre/@23.4596351,91.1759144,17z/data=!3m1!4b1!4m6!3m5!1s0x37547f26759e8171:0x66e643556d5d8d8c!8m2!3d23.4596351!4d91.1784893!16s%2Fg%2F11r8y2fh0",
          theme: "red",
          showAltPhone: true,
        },
        {
          name: "পপূলার ডায়াগনস্টিক সেন্টার",
          logo: "/popular-logo.png",
          address:
            "রুম ৫১২, ৫ম তলা (লিফট-৪), হাউজ নাম্বার ৫৭, লাকসাম রোড, রামঘাট, কান্দিরপাড়, কুমিল্লা ",
          days: "শনিবার থেকে বুধবার",
          time: "বিকেল ৫:০০ — রাত ৮:০০",
          offDays: "বৃহস্পতি ও শুক্রবার বন্ধ",
          mapUrl:
            "https://www.google.com/maps/place/Popular+Diagnostic+Centre,+Cumilla+Branch/@23.459514,91.1760966,17z/data=!4m6!3m5!1s0x37547f00462f8599:0x42aa888ebbe8dc!8m2!3d23.459514!4d91.1806027!16s%2Fg%2F11z4hvvkr6",
          theme: "green",
          showAltPhone: true,
        },
        {
          name: "ডক্টর’স পয়েন্ট ডায়াগনস্টিক সেন্টার",
          logo: "/doctorspoint-logo.png",
          address: "কালিকাপুর বাজার, বুড়িচং, কুমিল্লা",
          days: "শুধুমাত্র শুক্রবার",
          time: "সকাল ৮:০০ — রাত ৮:০০",
          offDays: "শনিবার থেকে বৃহস্পতিবার ",
          mapUrl:
            "https://www.google.com/maps/place/Doctors+Point+Diagnostic+%26+Consultation+Center/@23.5493469,88.8710592,8z/data=!4m6!3m5!1s0x375479003a0ff267:0x9c96e045ab925b3b!8m2!3d23.5493469!4d91.1781881!16s%2Fg%2F11z059n1m1",
          theme: "blue",
          showAltPhone: false,
        },
      ],
    },
  },
  {
    type: "testimonials",
    label: "রোগীর মতামত",
    description: "স্লাইডার আকারে রোগীদের রিভিউ",
    group: "page",
    icon: "quote",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      {
        key: "items",
        label: "মতামত তালিকা",
        type: "list",
        itemLabel: "মতামত",
        fields: [
          { key: "text", label: "মতামত", type: "textarea" },
          { key: "name", label: "নাম", type: "text" },
          { key: "address", label: "ঠিকানা", type: "text" },
        ],
      },
    ],
    defaults: {
      badge: "রোগীর মতামত",
      heading: "রোগীরা কী বলছেন",
      items: [
        {
          text: "অত্যন্ত অভিজ্ঞ এবং দক্ষ অর্থোপেডিক সার্জন। আমার হাঁটুর সমস্যা খুব দ্রুত সমাধান করেছেন। অত্যন্ত সেবাযত্ন সহকারে রোগীদের দেখেন।",
          name: "মো: রফিকুল ইসলাম",
          address: "কান্দিরপাড়, কুমিল্লা",
        },
        {
          text: "অনেক যত্ন সহকারে রোগীদের কথা শোনেন এবং বুঝিয়ে বলেন। চিকিৎসার মান অসাধারণ। সবার কাছে রেকমেন্ড করব।",
          name: "ফাতেমা বেগম",
          address: "শাসনগাছা, কুমিল্লা",
        },
        {
          text: "কোমর ব্যথার জন্য চিকিৎসা নিয়েছিলাম। খুব অল্প সময়েই ভাল ফল পেয়েছি। ডাক্তার স্যার অত্যন্ত আন্তরিক ও পেশাদার।",
          name: "জহিরুল হক",
          address: "বুড়িচং, কুমিল্লা",
        },
        {
          text: "আম্মার ফ্র্যাকচার অপারেশনের পর উনি এখন সম্পূর্ণ সুস্থ। স্যারের কাজের নিখুঁত দক্ষতা এবং সুন্দর ব্যবহার আমাদের মুগ্ধ করেছে।",
          name: "আহসান হাবিব",
          address: "বাগিচাগাও, কুমিল্লা",
        },
        {
          text: "হাঁটু প্রতিস্থাপন (Knee Replacement) অপারেশনের পর এখন আমি নিজে নিজেই হাঁটতে পারি। মহান আল্লাহর পর ডাক্তারের কাছে আমি কৃতজ্ঞ।",
          name: "সুফিয়া খাতুন",
          address: "চৌদ্দগ্রাম, কুমিল্লা",
        },
        {
          text: "দীর্ঘদিন ধরে স্পোর্টস ইনজুরিতে ভুগছিলাম। স্যারের পরামর্শ ও থেরাপিতে এখন আবার মাঠে ফিরতে পেরেছি। বেস্ট অর্থোপেডিক ডক্টর।",
          name: "শামীম আহমেদ",
          address: "ঝাউতলা, কুমিল্লা",
        },
        {
          text: "অন্য ডাক্তাররা অপারেশনের ভয় দেখিয়েছিল, কিন্তু স্যার সঠিক ওষুধের মাধ্যমে আমার ফ্রোজেন শোল্ডার একদম ঠিক করে দিয়েছেন।",
          name: "নুরজাহান বেগম",
          address: "লাকসাম, কুমিল্লা",
        },
        {
          text: "অত্যন্ত নম্র ও ভদ্র একজন মানুষ। প্রেসক্রিপশন দেওয়ার সময় প্রতিটা ওষুধের নিয়ম খুব সুন্দর করে বুঝিয়ে দেন।",
          name: "ডা. আরিফুর রহমান",
          address: "কুমিল্লা সদর",
        },
        {
          text: "হাতের কনুই ভাঙার পর এখানে অপারেশন করাই। প্লাস্টার কাটার পর এখন হাত আগের মতোই স্বাভাবিকভাবে নাড়াচড়া করতে পারছি।",
          name: "কামরুল হাসান",
          address: "বরুড়া, কুমিল্লা",
        },
        {
          text: "গেঁটে বাত বা আর্থ্রাইটিসের ব্যথায় রাতে ঘুমাতে পারতাম না। স্যারের চিকিৎসার পর এখন অনেক শান্তিতে ঘুমাতে পারি।",
          name: "হাজেরা আক্তার",
          address: "মুরাদনগর, কুমিল্লা",
        },
        {
          text: "অপারেশনের থিয়েটারে স্যার যেভাবে অভয় দিয়েছেন, আমার অর্ধেক ভয় ওখানেই কেটে গিয়েছিল। ওনার টিমও খুব হেল্পফুল।",
          name: "মো: সাহাব উদ্দিন",
          address: "চান্দিনা, কুমিল্লা",
        },
        {
          text: "বাচ্চার হাত মচকে যাওয়ার পর আপদকালীন সময়ে ওনাকে দেখাই। খুব দ্রুত ও যত্ন নিয়ে বাচ্চার চিকিৎসা করেছেন।",
          name: "রোকেয়া সুলতানা",
          address: "টমছম ব্রিজ, কুমিল্লা",
        },
        {
          text: "মেরুদণ্ডের ব্যথার জন্য অনেক জায়গায় দেখিয়েছি, কিন্তু এখানে এসে সঠিক ডায়াগনোসিস ও চিকিৎসা পেয়ে আমি এখন সুস্থ।",
          name: "আব্দুল মজিদ",
          address: "হোমনা, কুমিল্লা",
        },
        {
          text: "ফিজিওথেরাপি আর ওষুধের পারফেক্ট কম্বিনেশনে আমার সাইটিকার ব্যথা এখন আর নেই বললেই চলে। অনেক ধন্যবাদ স্যারকে।",
          name: "মনোয়ার হোসেন",
          address: "দাউদকান্দি, কুমিল্লা",
        },
        {
          text: "ডাক্তার দেখানোর পর ওনার ফলো-আপ গাইডলাইনগুলো দারুণ। রোগীকে সুস্থ না করা পর্যন্ত উনি খোঁজ নেন।",
          name: "সালমা বিনতে মাসুদ",
          address: "রেসকোর্স, কুমিল্লা",
        },
        {
          text: "পায়ের গোড়ালির লিগামেন্ট টিয়ার হয়েছিল। নিখুঁত আর্থ্রোস্কোপিক সার্জারির মাধ্যমে এখন আমি পুরোপুরি স্বাভাবিক।",
          name: "তারেক আজিজ",
          address: "দেবিদ্বার, কুমিল্লা",
        },
        {
          text: "কুমিল্লার মধ্যে অর্থোপেডিক চিকিৎসার জন্য ওনার চেয়ে আন্তরিক ও দক্ষ ডাক্তার দ্বিতীয় কেউ নেই। ওনার দীর্ঘায়ু কামনা করি।",
          name: "আলহাজ্ব মোস্তফা কামাল",
          address: "পদুয়ার বাজার, কুমিল্লা",
        },
        {
          text: "অহেতুক টেস্ট বা অপ্রয়োজনীয় ওষুধ দেন না। খুব সৎ এবং পেশাদার একজন রিলায়াবল চিকিৎসক।",
          name: "নাজমুল হুদা",
          address: "বাদুরতলা, কুমিল্লা",
        },
        {
          text: "ইউনিক চিকিৎসা পদ্ধতি। ওনার দেওয়া এক্সারসাইজগুলো নিয়মিত করার পর আমার পিঠের দীর্ঘদিনের পুরনো ব্যথা দূর হয়েছে।",
          name: "শাহানা পারভীন",
          address: "লাঙ্গলকোট, কুমিল্লা",
        },
        {
          text: "পেশেন্ট ডিলিং অসাধারণ। প্রথমবার দেখিয়েই মনে হয়েছে সঠিক জায়গায় এসেছি। প্রেসক্রিপশনও খুব সহজবোধ্য।",
          name: "ইমতিয়াজ আহমেদ",
          address: "কোতোয়ালী, কুমিল্লা",
        },
      ],
    },
  },
  {
    type: "videos",
    label: "ভিডিও গ্যালারি",
    description: "ভিডিও ট্যাব থেকে যুক্ত করা ইউটিউব ভিডিও দেখায়",
    group: "page",
    icon: "video",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "linkLabel", label: "লিংক টেক্সট", type: "text" },
      { key: "linkHref", label: "লিংক", type: "text" },
      { key: "count", label: "কতটি ভিডিও দেখাবে", type: "number" },
    ],
    defaults: {
      badge: "ভিডিও গ্যালারি",
      heading: "চিকিৎসা বিষয়ক ভিডিও",
      linkLabel: "সকল ভিডিওসমূহ",
      linkHref: "/our-videos",
      count: 4,
    },
  },
  {
    type: "blogs",
    label: "ব্লগ প্রিভিউ",
    description: "পোস্ট ট্যাব থেকে সর্বশেষ ব্লগ দেখায়",
    group: "page",
    icon: "post",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "linkLabel", label: "লিংক টেক্সট", type: "text" },
      { key: "linkHref", label: "লিংক", type: "text" },
      { key: "count", label: "কতটি ব্লগ দেখাবে", type: "number" },
    ],
    defaults: {
      badge: "স্বাস্থ্য টিপস",
      heading: "সর্বশেষ চিকিৎসা বিষয়ক পরামর্শ",
      linkLabel: "সকল ব্লগসমূহ",
      linkHref: "/our-blogs",
      count: 3,
    },
  },
  {
    type: "cta",
    label: "কল টু অ্যাকশন ব্যানার",
    description: "ফোন ও হোয়াটসঅ্যাপ বাটন সহ যোগাযোগ ব্যানার",
    group: "page",
    icon: "phone",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "body", label: "বিবরণ", type: "textarea" },
      { key: "phone", label: "ফোন নম্বর", type: "tel" },
      { key: "whatsappNumber", label: "হোয়াটসঅ্যাপ নম্বর", type: "text" },
      { key: "whatsappMessage", label: "হোয়াটসঅ্যাপ বার্তা", type: "textarea" },
      { key: "whatsappLabel", label: "হোয়াটসঅ্যাপ বাটন টেক্সট", type: "text" },
    ],
    defaults: {
      badge: "সরাসরি যোগাযোগ",
      heading: "আপনার সুস্থতাই আমাদের একমাত্র লক্ষ্য",
      body: "হাড়, জোড়া বা মেরুদণ্ডের যেকোনো সমস্যায় আর কষ্ট না পেয়ে আজই দেশের অভিজ্ঞ অর্থোপেডিক বিশেষজ্ঞের সিরিয়াল বুক করুন।",
      phone: "+8801858405083",
      whatsappNumber: "8801858405083",
      whatsappMessage:
        "আসসালামু আলাইকুম। আমি ডক্টর আরিফ ভেলিয়ার অ্যাপয়েন্টমেন্টের জন্য যোগাযোগ করছি।",
      whatsappLabel: "হোয়াটসঅ্যাপে বুক করুন",
    },
  },
  {
    type: "custom-richtext",
    label: "রিচ টেক্সট",
    description: "যেকোনো লেখা, শিরোনাম, তালিকা — নিজের মতো করে",
    group: "custom",
    icon: "text",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "html", label: "কন্টেন্ট", type: "richtext" },
      backgroundField,
      {
        key: "width",
        label: "প্রস্থ",
        type: "select",
        options: [
          { label: "সরু (পড়ার জন্য)", value: "narrow" },
          { label: "পূর্ণ", value: "full" },
        ],
      },
    ],
    defaults: {
      badge: "",
      heading: "নতুন সেকশন",
      html: "<p>এখানে আপনার লেখা যুক্ত করুন।</p>",
      background: "white",
      width: "narrow",
    },
  },
  {
    type: "custom-imagetext",
    label: "ছবি ও লেখা",
    description: "একপাশে ছবি, অন্যপাশে লেখা ও বাটন",
    group: "custom",
    icon: "image",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "html", label: "কন্টেন্ট", type: "richtext" },
      { key: "image", label: "ছবি", type: "image" },
      {
        key: "imagePosition",
        label: "ছবির অবস্থান",
        type: "select",
        options: [
          { label: "ডানে", value: "right" },
          { label: "বামে", value: "left" },
        ],
      },
      { key: "buttonLabel", label: "বাটন টেক্সট", type: "text" },
      { key: "buttonHref", label: "বাটন লিংক", type: "text" },
      backgroundField,
    ],
    defaults: {
      badge: "",
      heading: "শিরোনাম লিখুন",
      html: "<p>এখানে আপনার লেখা যুক্ত করুন।</p>",
      image: "/doctor-img.png",
      imagePosition: "right",
      buttonLabel: "",
      buttonHref: "",
      background: "white",
    },
  },
  {
    type: "custom-cardgrid",
    label: "কার্ড গ্রিড",
    description: "ছবি ও লেখাসহ কার্ডের গ্রিড (২/৩/৪ কলাম)",
    group: "custom",
    icon: "grid",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "subtitle", label: "উপশিরোনাম", type: "textarea" },
      {
        key: "columns",
        label: "কলাম সংখ্যা",
        type: "select",
        options: [
          { label: "২ কলাম", value: "2" },
          { label: "৩ কলাম", value: "3" },
          { label: "৪ কলাম", value: "4" },
        ],
      },
      { key: "showImages", label: "ছবি দেখাবেন?", type: "boolean" },
      {
        key: "items",
        label: "কার্ড তালিকা",
        type: "list",
        itemLabel: "কার্ড",
        fields: [
          { key: "title", label: "শিরোনাম", type: "text" },
          { key: "desc", label: "বিবরণ", type: "textarea" },
          { key: "image", label: "ছবি", type: "image" },
          { key: "href", label: "লিংক", type: "text" },
        ],
      },
      backgroundField,
    ],
    defaults: {
      badge: "",
      heading: "শিরোনাম লিখুন",
      subtitle: "",
      columns: "3",
      showImages: true,
      items: [
        { title: "কার্ড ১", desc: "বিবরণ লিখুন", image: "", href: "" },
        { title: "কার্ড ২", desc: "বিবরণ লিখুন", image: "", href: "" },
        { title: "কার্ড ৩", desc: "বিবরণ লিখুন", image: "", href: "" },
      ],
      background: "slate",
    },
  },
  {
    type: "custom-faq",
    label: "প্রশ্ন ও উত্তর",
    description: "অ্যাকর্ডিয়ন আকারে সাধারণ জিজ্ঞাসা",
    group: "custom",
    icon: "faq",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      {
        key: "items",
        label: "প্রশ্ন তালিকা",
        type: "list",
        itemLabel: "প্রশ্ন",
        fields: [
          { key: "q", label: "প্রশ্ন", type: "text" },
          { key: "a", label: "উত্তর", type: "textarea" },
        ],
      },
      backgroundField,
    ],
    defaults: {
      badge: "সাধারণ জিজ্ঞাসা",
      heading: "প্রায়শই জিজ্ঞাসিত প্রশ্ন",
      items: [{ q: "প্রশ্ন লিখুন", a: "উত্তর লিখুন" }],
      background: "white",
    },
  },
  {
    type: "custom-cta",
    label: "কাস্টম সিটিএ",
    description: "শিরোনাম ও দুটি বাটনসহ ব্যানার",
    group: "custom",
    icon: "phone",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "body", label: "বিবরণ", type: "textarea" },
      { key: "primaryLabel", label: "প্রথম বাটন", type: "text" },
      { key: "primaryHref", label: "প্রথম বাটন লিংক", type: "text" },
      { key: "secondaryLabel", label: "দ্বিতীয় বাটন", type: "text" },
      { key: "secondaryHref", label: "দ্বিতীয় বাটন লিংক", type: "text" },
      {
        key: "background",
        label: "ব্যাকগ্রাউন্ড",
        type: "select",
        options: [
          { label: "গ্রেডিয়েন্ট", value: "gradient" },
          { label: "গাঢ় নীল", value: "dark" },
        ],
      },
    ],
    defaults: {
      badge: "",
      heading: "শিরোনাম লিখুন",
      body: "",
      primaryLabel: "যোগাযোগ করুন",
      primaryHref: "tel:+8801858405083",
      secondaryLabel: "",
      secondaryHref: "",
      background: "gradient",
    },
  },
  {
    type: "custom-gallery",
    label: "ছবির গ্যালারি",
    description: "মিডিয়া থেকে বাছাই করা ছবির গ্রিড",
    group: "custom",
    icon: "gallery",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      {
        key: "source",
        label: "ছবির উৎস",
        type: "select",
        options: [
          { label: "গ্যালারি ট্যাব থেকে (স্বয়ংক্রিয়)", value: "gallery" },
          { label: "নিজে বাছাই করব", value: "manual" },
        ],
      },
      { key: "count", label: "সর্বোচ্চ কতটি ছবি", type: "number" },
      {
        key: "items",
        label: "ছবি তালিকা",
        type: "list",
        itemLabel: "ছবি",
        fields: [
          { key: "image", label: "ছবি", type: "image" },
          { key: "alt", label: "বিকল্প টেক্সট", type: "text" },
        ],
      },
      {
        key: "columns",
        label: "কলাম সংখ্যা",
        type: "select",
        options: [
          { label: "২ কলাম", value: "2" },
          { label: "৩ কলাম", value: "3" },
          { label: "৪ কলাম", value: "4" },
        ],
      },
      backgroundField,
    ],
    defaults: {
      badge: "",
      heading: "ছবির গ্যালারি",
      source: "gallery",
      count: 12,
      items: [],
      columns: "4",
      background: "white",
    },
  },
  {
    type: "custom-video",
    label: "ভিডিও এম্বেড",
    description: "নির্দিষ্ট ইউটিউব ভিডিও দেখান",
    group: "custom",
    icon: "video",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      {
        key: "items",
        label: "ভিডিও তালিকা",
        type: "list",
        itemLabel: "ভিডিও",
        fields: [
          { key: "url", label: "ইউটিউব লিংক", type: "url" },
          { key: "title", label: "শিরোনাম", type: "text" },
        ],
      },
      {
        key: "columns",
        label: "কলাম সংখ্যা",
        type: "select",
        options: [
          { label: "১ কলাম", value: "1" },
          { label: "২ কলাম", value: "2" },
          { label: "৩ কলাম", value: "3" },
        ],
      },
      backgroundField,
    ],
    defaults: {
      badge: "",
      heading: "ভিডিও",
      items: [],
      columns: "2",
      background: "slate",
    },
  },
  {
    type: "custom-counters",
    label: "সংখ্যা / কাউন্টার",
    description: "কয়েকটি সংখ্যা ও লেবেল পাশাপাশি",
    group: "custom",
    icon: "stats",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      {
        key: "items",
        label: "সংখ্যা তালিকা",
        type: "list",
        itemLabel: "সংখ্যা",
        fields: [
          { key: "value", label: "সংখ্যা", type: "text" },
          { key: "label", label: "লেবেল", type: "text" },
        ],
      },
      {
        key: "background",
        label: "ব্যাকগ্রাউন্ড",
        type: "select",
        options: [
          { label: "সাদা", value: "white" },
          { label: "হালকা ধূসর", value: "slate" },
          { label: "গাঢ় নীল", value: "dark" },
        ],
      },
    ],
    defaults: {
      badge: "",
      heading: "",
      items: [
        { value: "৫+", label: "বছরের অভিজ্ঞতা" },
        { value: "৫০০০+", label: "সফল সার্জারি" },
        { value: "৫০,০০০+", label: "সন্তুষ্ট রোগী" },
      ],
      background: "slate",
    },
  },
  {
    type: "custom-links",
    label: "লিংক তালিকা",
    description: "বাটন আকারে কয়েকটি লিংক",
    group: "custom",
    icon: "link",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      {
        key: "items",
        label: "লিংক তালিকা",
        type: "list",
        itemLabel: "লিংক",
        fields: linkFields,
      },
      backgroundField,
    ],
    defaults: {
      badge: "",
      heading: "গুরুত্বপূর্ণ লিংক",
      items: [{ label: "লিংক ১", href: "/" }],
      background: "white",
    },
  },
  {
    type: "custom-doctor-hero",
    label: "ডাক্তার হিরো",
    description: "ব্রেডক্রাম্ব, শিরোনাম, পরিসংখ্যান ও ছবিসহ পেজের শুরু",
    group: "custom",
    icon: "user",
    fields: [
      { key: "breadcrumbLabel", label: "ব্রেডক্রাম্ব লিংকের টেক্সট", type: "text" },
      { key: "breadcrumbHref", label: "ব্রেডক্রাম্ব লিংক", type: "text", placeholder: "/" },
      { key: "breadcrumbCurrent", label: "বর্তমান পেজের নাম", type: "text" },
      { key: "credentials", label: "ডিগ্রির লাইন", type: "text" },
      { key: "heading", label: "প্রধান শিরোনাম", type: "text" },
      { key: "headingEn", label: "শিরোনাম ইংরেজি ফন্টে", type: "boolean" },
      { key: "name", label: "ডাক্তারের নাম", type: "text" },
      { key: "position", label: "পদবি ও হাসপাতাল", type: "textarea" },
      {
        key: "stats",
        label: "পরিসংখ্যান",
        type: "list",
        itemLabel: "সংখ্যা",
        fields: [
          { key: "value", label: "সংখ্যা", type: "text" },
          { key: "label", label: "বিবরণ", type: "text" },
        ],
      },
      { key: "primaryLabel", label: "প্রথম বাটন", type: "text" },
      { key: "primaryHref", label: "প্রথম বাটন লিংক", type: "text" },
      { key: "secondaryLabel", label: "দ্বিতীয় বাটন", type: "text" },
      { key: "secondaryHref", label: "দ্বিতীয় বাটন লিংক", type: "text" },
      { key: "photo", label: "ডাক্তারের ছবি", type: "image" },
      { key: "photoAlt", label: "ছবির বিবরণ", type: "text" },
      backgroundField,
    ],
    defaults: {
      breadcrumbLabel: "হোম",
      breadcrumbHref: "/",
      breadcrumbCurrent: "কুমিল্লার সেরা অর্থোপেডিক ডাক্তার",
      credentials: "MBBS · BCS · MS (Orthopedic Surgery), BSMMU",
      heading: "Best Orthopedic Doctor in Cumilla",
      headingEn: true,
      name: "ডা. গাজী মোহাম্মদ আরিফুল ইসলাম (ভিলীয়া)",
      position: "সহকারী রেজিস্ট্রার, ক্যাজুয়ালটি বিভাগ — কুমিল্লা মেডিকেল কলেজ হাসপাতাল",
      stats: [
        { value: "5000+", label: "সফল সার্জারি" },
        { value: "1000+", label: "ট্রমা অপারেশন" },
        { value: "50,000+", label: "সন্তুষ্ট রোগী" },
        { value: "5+", label: "বছরের অভিজ্ঞতা" },
      ],
      primaryLabel: "অ্যাপয়েন্টমেন্ট নিন",
      primaryHref: "tel:+8801858405083",
      secondaryLabel: "হোয়াটসঅ্যাপে বুক করুন",
      secondaryHref: "https://wa.me/8801858405083",
      photo: "/doctor-img.png",
      photoAlt: "ডা. গাজী মোহাম্মদ আরিফুল ইসলাম",
      background: "white",
    },
  },
  {
    type: "custom-emergency",
    label: "জরুরি স্ট্রিপ",
    description: "জরুরি ট্রমা রোগীর জন্য সরু কল-স্ট্রিপ",
    group: "custom",
    icon: "phone",
    fields: [
      { key: "message", label: "বার্তা", type: "text" },
      { key: "buttonLabel", label: "বাটনের টেক্সট", type: "text" },
      { key: "phone", label: "ফোন নাম্বার", type: "tel" },
    ],
    defaults: {
      message: "দুর্ঘটনাজনিত জরুরি ট্রমা রোগীর জন্য — সরাসরি কল করুন",
      buttonLabel: "জরুরি লাইন: +8801612371696",
      phone: "+8801612371696",
    },
  },
  {
    type: "custom-cases",
    label: "রোগীর গল্প",
    description: "কেস স্টাডি কার্ড — ট্যাগ, শিরোনাম ও বিবরণ",
    group: "custom",
    icon: "document",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "subtitle", label: "বিবরণ", type: "textarea" },
      {
        key: "items",
        label: "কেসসমূহ",
        type: "list",
        itemLabel: "কেস",
        fields: [
          { key: "tag", label: "ট্যাগ", type: "text" },
          { key: "title", label: "শিরোনাম", type: "text" },
          { key: "body", label: "বিবরণ", type: "textarea" },
        ],
      },
      backgroundField,
    ],
    defaults: {
      badge: "রোগীর যাত্রা",
      heading: "রোগীর সুস্থতার গল্প",
      subtitle: "বাস্তব রোগীর অভিজ্ঞতা (রোগীর সম্মতিক্রমে, প্রয়োজনে নাম গোপন রাখা হয়েছে)।",
      items: [
        {
          tag: "CASE 01 — KNEE TREATMENT",
          title: "এক রোগীর গল্প: হাঁটুর তীব্র ব্যথা থেকে মুক্তি",
          body: "সমস্যা কী ছিল, কী চিকিৎসা দেওয়া হয়েছিল এবং বর্তমান অবস্থা — এখানে লিখুন।",
        },
        {
          tag: "CASE 02 — TRAUMA RECOVERY",
          title: "এক রোগীর গল্প: দুর্ঘটনা পরবর্তী সুস্থতা",
          body: "সমস্যা কী ছিল, কী চিকিৎসা দেওয়া হয়েছিল এবং বর্তমান অবস্থা — এখানে লিখুন।",
        },
      ],
      background: "white",
    },
  },
  {
    type: "custom-reviews",
    label: "রোগীর মন্তব্য ও ফেসবুক",
    description: "রিভিউ কার্ড ও নিচে ফেসবুক পেইজ প্যানেল",
    group: "custom",
    icon: "star",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "subtitle", label: "বিবরণ", type: "textarea" },
      {
        key: "columns",
        label: "কলাম",
        type: "select",
        options: [
          { label: "তিনটি", value: "3" },
          { label: "দুইটি", value: "2" },
        ],
      },
      {
        key: "items",
        label: "মন্তব্যসমূহ",
        type: "list",
        itemLabel: "মন্তব্য",
        fields: [
          { key: "quote", label: "মন্তব্য", type: "textarea" },
          { key: "author", label: "নাম ও এলাকা", type: "text" },
        ],
      },
      { key: "fbHeading", label: "ফেসবুক প্যানেল শিরোনাম", type: "text" },
      { key: "fbText", label: "ফেসবুক প্যানেল বিবরণ", type: "textarea" },
      {
        key: "fbStats",
        label: "ফেসবুক পরিসংখ্যান",
        type: "list",
        itemLabel: "সংখ্যা",
        fields: [
          { key: "value", label: "সংখ্যা", type: "text" },
          { key: "label", label: "বিবরণ", type: "text" },
        ],
      },
      { key: "fbLabel", label: "ফেসবুক বাটন", type: "text" },
      { key: "fbHref", label: "ফেসবুক পেইজ লিংক", type: "url" },
      backgroundField,
    ],
    defaults: {
      badge: "রোগীদের মতামত",
      heading: "রোগীদের অভিজ্ঞতার আলোকে তার চিকিৎসার মান",
      subtitle: "নিচের প্রতিটি মন্তব্য বাস্তব রোগীর — কোনো সাজানো রিভিউ নয়।",
      columns: "3",
      items: [
        {
          quote: "“অত্যন্ত অভিজ্ঞ এবং দক্ষ অর্থোপেডিক সার্জন। আমার হাঁটুর সমস্যা খুব দ্রুত সমাধান করেছেন।”",
          author: "মো: রফিকুল ইসলাম — কান্দিরপাড়",
        },
        {
          quote: "“কোমর ব্যথার জন্য চিকিৎসা নিয়েছিলাম। খুব অল্প সময়েই ভাল ফল পেয়েছি।”",
          author: "জহিরুল হক — বুড়িচং",
        },
        {
          quote: "“হাঁটু প্রতিস্থাপন অপারেশনের পর এখন আমি নিজে নিজেই হাঁটতে পারি।”",
          author: "সুফিয়া খাতুন — চৌদ্দগ্রাম",
        },
      ],
      fbHeading: "Facebook পেইজে আমাদের ফলো করুন",
      fbText: "রোগীদের মন্তব্য, আপডেট ও স্বাস্থ্য পরামর্শ পেতে পেইজটি ভিজিট করুন।",
      fbStats: [],
      fbLabel: "Facebook পেইজ দেখুন",
      fbHref: "https://web.facebook.com/people/Dr-Gazi-Arif-Velia/61564919693953/",
      background: "slate",
    },
  },
  {
    type: "custom-chambers",
    label: "চেম্বার ও সিরিয়াল",
    description: "ম্যাপ, ঠিকানা, সময় ও কল বাটনসহ চেম্বার কার্ড",
    group: "custom",
    icon: "home",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "subtitle", label: "বিবরণ", type: "textarea" },
      { key: "addressLabel", label: "ঠিকানার লেবেল", type: "text" },
      { key: "hoursLabel", label: "সময়ের লেবেল", type: "text" },
      { key: "phoneLabel", label: "ফোনের লেবেল", type: "text" },
      {
        key: "items",
        label: "চেম্বারসমূহ",
        type: "list",
        itemLabel: "চেম্বার",
        fields: [
          { key: "name", label: "নাম", type: "text" },
          { key: "address", label: "ঠিকানা", type: "textarea" },
          { key: "hours", label: "সময়", type: "text" },
          { key: "phone", label: "ফোন", type: "tel" },
          {
            key: "mapUrl",
            label: "Google Maps embed লিংক",
            type: "url",
            help: "Google Maps → Share → Embed a map → iframe-এর src অংশটি এখানে দিন।",
          },
          { key: "buttonLabel", label: "বাটনের টেক্সট", type: "text" },
        ],
      },
      backgroundField,
    ],
    defaults: {
      badge: "চেম্বার",
      heading: "চেম্বার ও সিরিয়াল",
      subtitle: "সুবিধাজনক লোকেশন থেকে সিরিয়াল নিয়ে দেখা করুন।",
      addressLabel: "ঠিকানা",
      hoursLabel: "সময়",
      phoneLabel: "ফোন",
      items: [
        {
          name: "কুমিল্লা ট্রমা সেন্টার",
          address: "রুম ৭০৬, ৭ম তলা, রাণীর বাজার রোড, কান্দিরপাড়",
          hours: "শনি–বুধ, দুপুর ২টা – বিকেল ৫টা",
          phone: "+8801612371696",
          mapUrl: "",
          buttonLabel: "কল করুন",
        },
        {
          name: "পপুলার ডায়াগনস্টিক সেন্টার",
          address: "রুম ৫১২, লাকসাম রোড, রামঘাট, কান্দিরপাড়",
          hours: "শনি–বুধ, বিকেল ৫টা – রাত ৮টা",
          phone: "+8801858405083",
          mapUrl: "",
          buttonLabel: "কল করুন",
        },
        {
          name: "ডক্টর’স পয়েন্ট ডায়াগনস্টিক সেন্টার",
          address: "কালিকাপুর বাজার, বুড়িচং, কুমিল্লা",
          hours: "শুধু শুক্রবার, সকাল ৮টা – রাত ৮টা",
          phone: "+8801612371696",
          mapUrl: "",
          buttonLabel: "কল করুন",
        },
      ],
      background: "white",
    },
  },
  {
    type: "custom-services",
    label: "সেবার গ্রিড",
    description: "হেয়ারলাইন গ্রিডে সেবার কার্ড ও নিচে একটি সিটিএ স্ট্রিপ",
    group: "custom",
    icon: "grid",
    fields: [
      { key: "badge", label: "ব্যাজ টেক্সট", type: "text" },
      { key: "heading", label: "শিরোনাম", type: "text" },
      { key: "subtitle", label: "বিবরণ", type: "textarea" },
      {
        key: "columns",
        label: "কলাম",
        type: "select",
        options: [
          { label: "তিনটি", value: "3" },
          { label: "দুইটি", value: "2" },
        ],
      },
      {
        key: "items",
        label: "সেবাসমূহ",
        type: "list",
        itemLabel: "সেবা",
        fields: [
          { key: "title", label: "নাম", type: "text" },
          { key: "desc", label: "সংক্ষিপ্ত বিবরণ", type: "textarea" },
          { key: "href", label: "লিংক", type: "text", placeholder: "/our-treatments/knee-pain-treatment-cumilla" },
          { key: "linkLabel", label: "লিংকের টেক্সট", type: "text", placeholder: "বিস্তারিত" },
          { key: "highlight", label: "গাড় কার্ড হিসেবে দেখান", type: "boolean" },
        ],
      },
      { key: "ctaHeading", label: "সিটিএ শিরোনাম", type: "text" },
      { key: "ctaText", label: "সিটিএ বিবরণ", type: "textarea" },
      { key: "ctaLabel", label: "সিটিএ বাটন", type: "text" },
      { key: "ctaHref", label: "সিটিএ লিংক", type: "text", placeholder: "/" },
      backgroundField,
    ],
    defaults: {
      badge: "চিকিৎসা সেবা",
      heading: "আমাদের চিকিৎসা সেবাসমূহ",
      subtitle:
        "হাঁটু থেকে মেরুদণ্ড — প্রতিটি হাড় ও জোড়ার সমস্যার আধুনিক ও নির্ভরযোগ্য চিকিৎসা।",
      columns: "3",
      items: [
        {
          title: "হাঁটু ব্যথা",
          desc: "হাঁটুর লিগামেন্ট, কার্টিলেজ ও বিভিন্ন জটিলতার আধুনিক চিকিৎসা।",
          href: "/our-treatments/knee-pain-treatment-cumilla",
          linkLabel: "বিস্তারিত",
        },
        {
          title: "কোমর ও মেরুদণ্ড",
          desc: "ডিস্ক প্রোল্যাপ্স, সাইটিকা ও মেরুদণ্ডের তীব্র ব্যথা ব্যবস্থাপনা।",
          href: "/our-treatments/back-pain-treatment-cumilla",
          linkLabel: "বিস্তারিত",
        },
        {
          title: "কাঁধ ও জয়েন্টের সমস্যা",
          desc: "ফ্রোজেন শোল্ডার, কাঁধের জয়েন্ট ও পেশির দীর্ঘমেয়াদী সমস্যার সমাধান।",
          href: "/our-treatments/shoulder-joint-pain-treatment-cumilla",
          linkLabel: "বিস্তারিত",
        },
        {
          title: "স্পোর্টস ইনজুরি",
          desc: "খেলোয়াড়দের পেশি ও লিগামেন্ট ইনজুরির বিশেষায়িত আধুনিক চিকিৎসা।",
          href: "/our-treatments/sports-injury-treatment-cumilla",
          linkLabel: "বিস্তারিত",
        },
        {
          title: "মেরুদণ্ডের সমস্যা ও ট্রমা",
          desc: "দুর্ঘটনাজনিত হাড় ভাঙা, স্থানচ্যুতি ও জটিল ট্রমা সার্জারি পরবর্তী সেবা।",
          href: "/our-treatments/spine-trauma-treatment-cumilla",
          linkLabel: "বিস্তারিত",
        },
        {
          title: "হাতের কব্জি ও পায়ের পাতা",
          desc: "কব্জি, পায়ের গোড়ালি ও রগ বা পেশির নানান রোগের সমাধান।",
          href: "/our-treatments/wrist-foot-pain-treatment-cumilla",
          linkLabel: "বিস্তারিত",
        },
      ],
      ctaHeading: "পুরো ক্লিনিক ও সব ডাক্তারের তথ্য একসাথে দেখতে চান?",
      ctaText:
        "ডা. গাজী মোহাম্মদ আরিফুল ইসলাম (ভিলীয়া)-এর সম্পূর্ণ ওয়েবসাইটে সব বিভাগ, পরিচিতি ও যোগাযোগের তথ্য পাবেন।",
      ctaLabel: "হোম পেজে যান",
      ctaHref: "/",
      background: "white",
    },
  },
  {
    type: "custom-html",
    label: "কাস্টম HTML + CSS",
    description: "নিজের HTML ও CSS — CSS শুধু এই সেকশনেই কাজ করবে",
    group: "custom",
    icon: "code",
    fields: [
      {
        key: "html",
        label: "HTML",
        type: "code",
        placeholder: '<div class="box">\n  <h3>শিরোনাম</h3>\n</div>',
        help: "স্ক্রিপ্ট, iframe ও ইভেন্ট হ্যান্ডলার বাদ দেওয়া হয়।",
      },
      {
        key: "css",
        label: "CSS",
        type: "code",
        placeholder: ".box {\n  padding: 24px;\n  border-radius: 12px;\n}",
        help: "সাধারণ CSS লিখুন। প্রতিটি সিলেক্টর স্বয়ংক্রিয়ভাবে এই সেকশনে সীমাবদ্ধ থাকে, অন্য কোথাও প্রভাব ফেলে না।",
      },
      {
        key: "container",
        label: "প্রস্থ",
        type: "select",
        options: [
          { label: "সাইটের সাধারণ প্রস্থ", value: "default" },
          { label: "সরু", value: "narrow" },
          { label: "সম্পূর্ণ প্রস্থ", value: "full" },
        ],
      },
      backgroundField,
    ],
    defaults: {
      html: "",
      css: "",
      container: "default",
      background: "white",
    },
  },
];

export const BLOCK_MAP: Record<string, BlockDefinition> = Object.fromEntries(
  BLOCKS.map((b) => [b.type, b]),
);

export function getBlock(type: string): BlockDefinition | undefined {
  return BLOCK_MAP[type];
}

export function blockDefaults<T = Record<string, unknown>>(type: string): T {
  return JSON.parse(JSON.stringify(BLOCK_MAP[type]?.defaults ?? {})) as T;
}

export const CUSTOM_BLOCKS = BLOCKS.filter((b) => b.group === "custom");
export const PAGE_BLOCKS = BLOCKS.filter((b) => b.group === "page" && !b.fixed);
